# Generated by Django 5.1.5 on 2025-02-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('SALAIRE', 'Salaire'), ('EAU', 'Eau'), ('ELECTRICITE', 'Électricité'), ('LOYER', 'Loyer'), ('TRANSPORT', 'Transport'), ('APPROVISIONNEMENT', 'Approvisionnement Produit'), ('AUTRE', 'Autre')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('CASH', 'Cash')], max_length=20)),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='pieces_justificatives/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
